apiVersion: apps/v1
kind: Deployment
metadata:
  name: role-service
  labels:
    app: role
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: role
  template:
    metadata:
      labels:
        app: role
    spec:
      containers:
      - name: role-service
        image: reabaln/role-service
        ports:
        - containerPort: 80
