apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-service
  labels:
    app: office
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office
  template:
    metadata:
      labels:
        app: office
    spec:
      containers:
      - name: office-service
        image: reabaln/office-service
        ports:
        - containerPort: 80
